name: SBOM scan (POC)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  generate_sbom:
    runs-on: ubuntu-latest
    name: "SBOM Generation & Notify"
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate SBOM
        id: sbom_generation
        uses: codenotary/sbom.sh-create@main
        with:
          scan_type: grypefs
          target: .
          output-format: json

      - name: Post results to POC webhook
        run: |
          echo "${{ steps.sbom_generation.outputs.sbom_json }}" > sbom.json
          curl -sSL -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$(openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" sbom.json | cut -d' ' -f2)" \
            --data @sbom.json
